#!/bin/bash

# Create a release using the Jenkins release automation!

script=$(basename "$0")
if [ "$#" -ne 2 ]; then
    echo "Usage $script <base-branch> <x.y>"
    echo "<base-branch> - the branch ontop which the release is placed."
    echo "<x.y> - version major (x) and minor (y), patch (z) is generated by Jenkins!"
    exit 1
fi

base_branch=$1
version=$2

if ! git diff-index --quiet HEAD ; then
    # Note: this ignores untracked files!
    echo "Git working directory not clean!"
    exit 1
fi

if ! echo "$version" | grep -P -q "^(\d+\.)(\d+)$" ; then
    echo "Version $version malformed for a jenkins release branch name! Use <x.y>!"
    exit 1
fi

if ! git checkout "$base_branch" ; then
    echo "Failed to checkout base branch: $base_branch"
    exit 1
fi

release_branch="release/$version"
if ! git checkout -b "$release_branch" ; then
    echo "Failed to create release branch $release_branch"
    exit 1
fi

if ! git push --set-upstream origin "$release_branch" ; then
    echo "Failed to push release branch $release_branch"
    exit 1
fi

echo "*************************+"
echo "Release branch created and pushed to git."
echo "Please check Jenkins for release progress and success!"
echo "*************************+"
